apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-fights
    application: fights-service
    system: quarkus-super-heroes
  name: rest-fights-config
data:
  quarkus.liquibase-mongodb.migrate-at-start: "false"
  quarkus.mongodb.hosts: fights-db:27017
  quarkus.stork.hero-service.service-discovery.type: static
  quarkus.stork.hero-service.service-discovery.address-list: rest-heroes.quarkus-superheroes.svc.cluster.local:80
  quarkus.stork.villain-service.service-discovery.type: static
  quarkus.stork.villain-service.service-discovery.address-list: rest-villains.quarkus-superheroes.svc.cluster.local:80
  quarkus.opentelemetry.tracer.exporter.otlp.endpoint: http://otel-collector:4317
  kafka.bootstrap.servers: 'PLAINTEXT://fights-kafka-kafka-bootstrap:9092'
  mp.messaging.connector.smallrye-kafka.apicurio.registry.url: http://apicurio:8080/apis/registry/v2