apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ui-super-heroes
  namespace: super-heroes-serverless
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true" 
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
#      labels:
#        app: ui-super-heroes
#        version: v1
    spec:
      containerConcurrency: 0
      containers:
        - image: 'quay.io/quarkus-super-heroes/ui-super-heroes'
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300