apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cluster-configs
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster
    repoURL: 'https://github.com/cainza/openshift-app-dev-demo.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated: {}