apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: 2Xv9xiYdpSbcVDTNtZL4sHg6ulJWj8mU
  #ARGOCD_AUTH_TOKEN: <token>