apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: YWRtaW4K
  ARGOCD_PASSWORD: Mlh2OXhpWWRwU2JjVkRUTnRaTDRzSGc2dWxKV2o4bVUK
  #ARGOCD_AUTH_TOKEN: <token>