kind: Secret
apiVersion: v1
metadata:
  name: argocd-env-secret
  namespace: quarkus-superheroes-serverless
data:
  ARGOCD_PASSWORD: Mlh2OXhpWWRwU2JjVkRUTnRaTDRzSGc2dWxKV2o4bVU=
  ARGOCD_USERNAME: YWRtaW4=
type: Opaque
