apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-superheroes
  namespace: quarkus-superheroes-serverless
spec:
  tasks:
    - name: clone-superheroes
      params:
        - name: url
          value: 'https://github.com/quarkusio/quarkus-super-heroes.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:5b36e9d4ddffa4c253c47e444b7d3158bbbd2a3acf3c301389f6c50cbf5e8086
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-build-event-statistics
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-DskipTests=true'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: event-statistics
      runAfter:
        - clone-superheroes
      taskRef:
        kind: Task
        name: maven-demo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: maven-build-rest-heroes
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-DskipTests=true'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: rest-heroes
      runAfter:
        - clone-superheroes
      taskRef:
        kind: Task
        name: maven-demo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: maven-build-rest-villains
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-DskipTests=true'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: rest-villains
      runAfter:
        - clone-superheroes
      taskRef:
        kind: Task
        name: maven-demo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: maven-build-rest-fights
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-DskipTests=true'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - clone-superheroes
      taskRef:
        kind: Task
        name: maven-demo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-rest-fights-image
      params:
        - name: IMAGE
          value: 'rest-fights:latest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm17
        - name: CONTEXT
          value: event-statistics
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build-rest-fights
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-rest-villains-image
      params:
        - name: IMAGE
          value: 'rest-villains:latest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm17
        - name: CONTEXT
          value: rest-villains
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build-rest-villains
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-rest-heroes-image
      params:
        - name: IMAGE
          value: 'rest-heroes:latest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm17
        - name: CONTEXT
          value: rest-heroes
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build-rest-heroes
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-event-statistics-image
      params:
        - name: IMAGE
          value: 'event-statistics:latest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm17
        - name: CONTEXT
          value: event-statistics
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build-event-statistics
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-ui-super-heroes-image
      params:
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: IMAGE
          value: 'ui-super-heroes:latest'
      runAfter:
        - build-rest-fights-image
        - build-rest-villains-image
        - build-rest-heroes-image
        - build-event-statistics-image
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: false
    - name: maven-settings
      optional: false
  params: []
  resources: []
  finally: []
