---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: 00-quarkus-superheroes
  namespace: quarkus-superheroes-serverless
spec:
  tasks:
    - name: prepare-maven
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:4c0e850cdcf91a94a726be5e1fc1893be9b00e4210214dbef19bfc9240c13fa4
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - 'pipeline   '
            - start
            - 01-prepare-maven
            - '--workspace name=shared-workspace-pvc,claimName=shared-workspace'
            - '--workspace name=maven-settings-cm,config=maven-settings-cm'
            - '--workspace name=mvn-cache-pvc,claimName=mvn-cache '
            - '--showlog'
            - '--use-param-defaults'
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: build-event-statistics
      runAfter:
        - prepare-maven
      taskRef:
        kind: ClusterTask
        name: tkn
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:4c0e850cdcf91a94a726be5e1fc1893be9b00e4210214dbef19bfc9240c13fa4
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - 'pipeline   '
            - start
            - 02-event-statistics
            - '--workspace name=shared-workspace-pvc,claimName=shared-workspace'
            - '--workspace name=maven-settings-cm,config=maven-settings-cm'
            - '--workspace name=mvn-cache-pvc,claimName=mvn-cache '
            - '--showlog'
            - '--use-param-defaults'
    - name: rest-heroes
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:4c0e850cdcf91a94a726be5e1fc1893be9b00e4210214dbef19bfc9240c13fa4
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - 'pipeline   '
            - start
            - 03-rest-heroes
            - '--workspace name=shared-workspace-pvc,claimName=shared-workspace'
            - '--workspace name=maven-settings-cm,config=maven-settings-cm'
            - '--workspace name=mvn-cache-pvc,claimName=mvn-cache '
            - '--showlog'
            - '--use-param-defaults'
      runAfter:
        - build-event-statistics
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: rest-villains
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:4c0e850cdcf91a94a726be5e1fc1893be9b00e4210214dbef19bfc9240c13fa4
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - 'pipeline   '
            - start
            - 04-rest-villains
            - '--workspace name=shared-workspace-pvc,claimName=shared-workspace'
            - '--workspace name=maven-settings-cm,config=maven-settings-cm'
            - '--workspace name=mvn-cache-pvc,claimName=mvn-cache '
            - '--showlog'
            - '--use-param-defaults'
      runAfter:
        - rest-heroes
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: rest-fights
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:4c0e850cdcf91a94a726be5e1fc1893be9b00e4210214dbef19bfc9240c13fa4
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - 'pipeline   '
            - start
            - 05-rest-fights
            - '--workspace name=shared-workspace-pvc,claimName=shared-workspace'
            - '--workspace name=maven-settings-cm,config=maven-settings-cm'
            - '--workspace name=mvn-cache-pvc,claimName=mvn-cache '
            - '--showlog'
            - '--use-param-defaults'
      runAfter:
        - rest-villains
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: ui-super-heroes
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:4c0e850cdcf91a94a726be5e1fc1893be9b00e4210214dbef19bfc9240c13fa4
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - 'pipeline   '
            - start
            - 06-ui-super-heroes
            - '--workspace name=shared-workspace-pvc,claimName=shared-workspace'
            - '--workspace name=maven-settings-cm,config=maven-settings-cm'
            - '--workspace name=mvn-cache-pvc,claimName=mvn-cache '
            - '--showlog'
            - '--use-param-defaults'
      runAfter:
        - rest-fights
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: sync-quarkus-superheroes
      params:
        - name: application-name
          value: quarkus-superheroes
        - name: revision
          value: HEAD
        - name: flags
          value: '--'
        - name: argocd-version
          value: v2.2.2
      runAfter:
        - ui-super-heroes
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait