apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: quarkus-superheroes-tekton
  name: 04-rest-villains
  namespace: quarkus-superheroes-serverless
spec:
  params:
    - default: >-
        image-registry.openshift-image-registry.svc:5000/quarkus-superheroes-serverless
      name: image_base_url
      type: string
  tasks:
    - name: clone-superheroes
      params:
        - name: url
          value: 'https://github.com/quarkusio/quarkus-super-heroes.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:5b36e9d4ddffa4c253c47e444b7d3158bbbd2a3acf3c301389f6c50cbf5e8086
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace-pvc
    - name: maven-build-rest-villains
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-DskipTests=true'
            - '-Dmaven.artifact.threads=30'
            - '-Dmaven.repo.local=/media/.m2/'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: rest-villains
      runAfter:
        - maven-download-dependencies
      taskRef:
        kind: Task
        name: maven-demo
      workspaces:
        - name: source
          workspace: shared-workspace-pvc
        - name: maven-settings
          workspace: maven-settings-cm
        - name: mvn-cache
          workspace: mvn-cache-pvc
    - name: build-rest-villains-image
      params:
        - name: IMAGE
          value: '$(params.image_base_url)/rest-villains:latest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm17
        - name: CONTEXT
          value: rest-villains
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build-rest-villains
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace-pvc
    - name: maven-download-dependencies
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - 'dependency:resolve'
            - '-Dmaven.repo.local=/media/.m2/'
            - '-Dmaven.artifact.threads=30'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: rest-villains
      runAfter:
        - clone-superheroes
      taskRef:
        kind: Task
        name: maven-demo
      workspaces:
        - name: source
          workspace: shared-workspace-pvc
        - name: mvn-cache
          workspace: mvn-cache-pvc
        - name: maven-settings
          workspace: maven-settings-cm
  workspaces:
    - name: shared-workspace-pvc
      optional: false
    - name: maven-settings-cm
      optional: false
    - name: mvn-cache-pvc
      optional: false
  resources: []
  finally: []
