kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-workspace
  namespace: quarkus-superheroes-serverless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mvn-cache
  namespace: quarkus-superheroes-serverless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 100Gi
