kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-workspace
  namespace: quarkus-superheroes-serverless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mvn-cache
  namespace: quarkus-superheroes-serverless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
