apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: petstore-tenant
  namespace: 3scale-petstore
spec:
  email: 3scale-petstore@apps-crc.testing
  masterCredentialsRef:
    name: system-seed
  organizationName: 3scale-petstore
  passwordCredentialsRef:
    name: ecorp-admin-secret
  systemMasterUrl: 'https://master.apps-crc.testing/'
  tenantSecretRef:
    name: ecorp-tenant-secret
    namespace: operator-test
  username: admin@apps-crc.testing
