---

# Check if CRC is already set up
#crc status
#CRC VM:          Running
#OpenShift:       Running (v4.10.22)
#Podman:          
#Disk Usage:      24.63GB of 267.9GB (Inside the CRC VM)
#Cache Usage:     51.04GB
#Cache Directory: /home/francis/.crc/cache

- debug:
    msg: "Configuring CRC Environment"

- name: Enable / Disable Telemetry to Red Hat
  command: crc config set consent-telemetry '{{ crc_consent_telemetry }}'

- name: Enable / Disable Cluster Monitoring  # Enable only if you have enough memory, needs ~4G extra
  command: crc config set enable-cluster-monitoring '{{ crc_cluster_monitoring }}'

- name: Set CRC CPU's
  command: crc config set cpus '{{ crc_cpus }}'

- name: Set CRC Memory
  command: crc config set memory '{{ crc_memory }}'

- name: Set Disk Size, Thin Provisioned
  command: crc config set disk-size '{{ crc_disk_size }}'

- name: "Show config"
  command: crc config view
  register: crc_config_output

- debug:
    var: crc_config_output.stdout_lines