apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: 06-ui-super-heroes
  labels:
    app.kubernetes.io/instance: quarkus-superheroes-tekton
spec:
  params:
    - default: >-
        image-registry.openshift-image-registry.svc:5000/quarkus-superheroes
      name: image_base_url
      type: string
  tasks:
    - name: clone-superheroes
      params:
        - name: url
          value: 'https://github.com/quarkusio/quarkus-super-heroes.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:5b36e9d4ddffa4c253c47e444b7d3158bbbd2a3acf3c301389f6c50cbf5e8086
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace-pvc
    - name: build-ui-super-heroes-image
      params:
        - name: IMAGE
          value: '$(params.image_base_url)/ui-super-heroes:latest'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: Dockerfile
        - name: CONTEXT
          value: ui-super-heroes
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - clone-superheroes
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace-pvc
  workspaces:
    - name: shared-workspace-pvc
    - name: maven-settings-cm
    - name: mvn-cache-pvc
