#kind: Secret
#apiVersion: v1
#metadata:
#  name: init-config-bundle-secret
#  namespace: quay-demo
#data:
#  config.yaml: >-
#    RkVBVFVSRV9VU0VSX0lOSVRJQUxJWkU6IHRydWUKQlJPV1NFUl9BUElfQ0FMTFNfWEhSX09OTFk6IGZhbHNlClNVUEVSX1VTRVJTOgotIHF1YXlhZG1pbgpGRUFUVVJFX1VTRVJfQ1JFQVRJT046IGZhbHNlCkZFQVRVUkVfUVVPVEFfTUFOQUdFTUVOVDogdHJ1ZQpGRUFUVVJFX0JVSUxEX1NVUFBPUlQ6IHRydWUKRkVBVFVSRV9QUk9YWV9DQUNIRTogdHJ1ZQpGRUFUVVJFX1NUT1JBR0VfUkVQTElDQVRJT046IHRydWUKREVGQVVMVF9TWVNURU1fUkVKRUNUX1FVT1RBX0JZVEVTOiAxMDI0MDAwMDAK
#type: Opaque
