apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ratings-v1
#  namespace: bookinfo-serverless
#  annotations:
#    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/inject: "true" 
#        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: ratings
        version: v1
    spec:
      containerConcurrency: 0
      containers:
        - image: 'quay.io/maistra/examples-bookinfo-ratings-v1:2.2.0'
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          command: ["node"]
          args: ["/opt/microservices/ratings.js", "8080"]
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300