apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
    namespace: openshift-operators
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: operators/openshift-operators
    repoURL: 'https://github.com/cainza/openshift-app-dev-demo.git'
    targetRevision: development
  syncPolicy:
    automated: {}
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
