apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mta-wlcq7
  namespace: mta
spec:
  targetNamespaces:
  - mta
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mta-operator
  namespace: mta
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: mta-operator
  source: community-operators
  sourceNamespace: openshift-marketplace