---
- debug:
    msg: "Deploying Gitops Operator"

- name: Create Operator Subscription for Openshift GitOps Operator
  community.okd.k8s:
    state: present
    src: openshift-gitops-operator.yaml

- debug:
    msg: "Waiting for Gitops Operator to become ready"

- name: Check if Operator Subscription has finished / Succeeded
  monitor_operator_install:
    name: openshift-gitops-operator
    namespace: openshift-operators
