---
- name: CRC Setup
  debug:
    msg: "Setting up CRC Environment"

- name: Running crc setup
  command: crc setup

- name: Start CRC
  command: crc start

- name: Check Logged in with {{ crc_admin_user }}
  command: oc whoami
  register: crcuser
  failed_when: "'{{ crc_admin_user }}' not in crcuser.stdout"