---
- debug:
    msg: "Sync Service Mesh GitOps Application"

- sync_gitops_application:
    namespace: openshift-gitops
    secret: openshift-gitops-cluster
    url: openshift-gitops-server-openshift-gitops.apps-crc.testing
    port: 443
    application: 1-istio-controlplane

- debug:
    msg: "Monitoring Service Mesh to Become Ready"

- monitor_operator_custom_resource:
    name: basic
    namespace: istio-system
    group: maistra.io
    version: v2
    plural: servicemeshcontrolplanes

