---
- debug:
    msg: "Sync Service Mesh GitOps Application"

- sync_gitops_application:
    namespace: openshift-gitops
    secret: openshift-gitops-cluster
    url: openshift-gitops-server-openshift-gitops.apps-crc.testing
    port: 443
    application: 1-istio-controlplane

- custom_resource_deployment:
    