---
- debug:
    msg: "Monitor Kiali operator is installed"

- name: Check if Kiali Operator is installed
  monitor_operator_install:
    name: kiali-ossm
    namespace: openshift-operators

- debug:
    msg: "Elasticsearch operator is installed"

- name: Check if Elasticsearch Operator is installed
  monitor_operator_install:
    name: elasticsearch-operator
    namespace: openshift-operators-redhat

- debug:
    msg: "Monitor Jaeger operator is installed"

- name: Check if Jaeger Operator is installed
  monitor_operator_install:
    name: jaeger-product
    namespace: openshift-distributed-tracing

- debug:
    msg: "Monitor service mesh operator is installed"

- name: Check if Service Mesh Operator is installed
  monitor_operator_install:
    name: servicemeshoperator
    namespace: openshift-operators

- debug:
    msg: "Sync Service Mesh GitOps Application"

- sync_gitops_application:
    namespace: openshift-gitops
    secret: openshift-gitops-cluster
    url: openshift-gitops-server-openshift-gitops.apps-crc.testing
    port: 443
    application: 1-istio-controlplane

- debug:
    msg: "Monitoring Service Mesh to Become Ready"


