apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fights-kafka
  namespace: quarkus-superheroes-serverless
spec:
  kafka:
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: '3.1'
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    resources:
#      limits:
#        cpu: 200m
#        memory: 256Mi
#      requests:
#        memory: 256Mi
    storage:
      type: ephemeral
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    replicas: 1
    version: 3.1.0
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: ephemeral
#    jvmOptions:
#      '-Xms': 256m
#      '-Xmx': 256m
    replicas: 1