kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: odf-lvm-odf-lvm-vg-immediate
  annotations:
    description: Provides RWO and RWOP Filesystem & Block volumes
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: topolvm.cybozu.com
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.cybozu.com/device-class: odf-lvm-vg
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate