apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - knative-serving # Must always be there to work - DO NOT DELETE
  - quarkus-superheroes-serverless
  - quarkus-superheroes