---
- name: ArgoCD Route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ openshift_argocd_gitops_route }}"
    namespace: "{{ openshift_argocd_namespace }}"
  register: argocdroute

- name: Create Cluster Demo Applications in GitOps
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: knative-serving
        namespace: "{{ openshift_argocd_namespace }}"
      spec:
        destination:
          namespace: knative-serving
          server: https://kubernetes.default.svc
        project: "{{ cluster_demo_setup_project }}"
        source:
          path: demo/knative/knative-serving
          repoURL: "{{ cluster_demo_setup_repo }}"
          targetRevision: "{{ cluster_demo_setup_revision }}"
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true


- name: Knative GitOps Application
  debug:
    msg: "Sync Knative GitOps Application"

- sync_gitops_application:
    namespace: "{{ openshift_argocd_namespace }}"
    secret: "{{ openshift_argocd_secret }}"
    url: "{{argocdroute.resources[0].spec.host}}"
    port: 443
    application: knative-serving

- name: Waiting for Knative Serving
  debug:
    msg: "Monitoring Knative Serving to Become Ready"

- monitor_operator_custom_resource:
    name: "{{ knative_name }}"
    namespace: knative-serving
    group: "{{ knative_apigroup }}"
    version: "{{ knative_apiversion }}"
    plural: knativeservings
