- hosts: ocp
  connection: local
  gather_facts: false
  vars_prompt:
    - name: OCP_api_server
      prompt: "Please enter your openshift location ( example: https://api.openshift.local:6443)"
      private: no
    - name: OCP_username
      prompt: Please enter your OCP user (With cluster-admin rights)
      private: no
    - name: OCP_password
      prompt: Please enter your OCP user's password (Output will be hidden)
  pre_tasks:
    - set_fact:
        OCP_api_server: "{{OCP_api_server}}"
    - set_fact:
        OCP_username: "{{OCP_username}}"
    - set_fact:
        OCP_password: "{{OCP_password}}"
    - name: Check OCP Version
      ansible.builtin.command: "{% raw %}oc get clusterversion/version --no-headers --template={{.status.desired.version}}{% endraw %}"
      register: ocp_version
      failed_when: ocp_version.stdout != "4.11.1"

  roles:
    #- openshift-login
    #- openshift-gitops
    #- argocd-client-install
    #- cluster-demo
    #- sno-local-storage
    - sno-odf-lvm
    #- sno-odf-mcg
    #- sync-gitops-application-servicemesh
    #- sync-gitops-application-knative-serving
    #- sync-gitops-application-tekton
    #- sync-gitops-application-quarkus-superheroes
    - argocd-get-login

    # TODO
    # - Quarkus Superheroes rest-fights route for UI dynamic